version: '3.8'

services:
  tc-server:
    build:
      context: ./
      dockerfile: Dockerfile_TC
    restart: always
    environment:
      TCGUI_IP: 0.0.0.0
      TCGUI_PORT: 5000
    cap_add:
      - NET_ADMIN
    depends_on:
      - openvpn_client_with_tc
    network_mode: "service:openvpn_client_with_tc"

  openvpn_client_no_tc:
    container_name: openvpn_client_no_tc
    build:
      context: ./
      dockerfile: Dockerfile_openvpn_client
    cap_add:
      - NET_ADMIN
    security_opt:
      - label:disable
    volumes:
      - /dev/net:/dev/net:z
      - ./vpn/openvpn_client_no_tc.ovpn:/vpn/openvpn_client_no_tc.ovpn:ro
    environment:
      TZ: 'EST5EDT'
    restart: unless-stopped
    read_only: true
    stdin_open: true
    tty: true
    tmpfs:
      - /run
      - /tmp
    networks:
      no_tc_net:
        ipv4_address: 10.9.91.200  # Ensure this IP is not in use
      vpn_net:
        ipv4_address: 10.9.96.101  # Ensure this IP is not in use
    command: /bin/bash -c "openvpn --config /vpn/openvpn_client_no_tc.ovpn && ip route add default via 80.240.24.18 dev eth0"

  openvpn_client_with_tc:
    container_name: openvpn_client_with_tc
    build:
      context: ./
      dockerfile: Dockerfile_openvpn_client
    cap_add:
      - NET_ADMIN
    security_opt:
      - label:disable
    volumes:
      - /dev/net:/dev/net:z
      - ./vpn/openvpn_client_with_tc.ovpn:/vpn/openvpn_client_with_tc.ovpn:ro
    environment:
      TZ: 'EST5EDT'
    restart: unless-stopped
    read_only: true
    stdin_open: true
    tty: true
    tmpfs:
      - /run
      - /tmp
    ports:
      - 5000:5000
    networks:
      tc_net:
        ipv4_address: 10.9.92.200  # Ensure this IP is not in use
      vpn_net:
        ipv4_address: 10.9.96.102  # Ensure this IP is not in use
    command: /bin/bash -c "openvpn --config /vpn/openvpn_client_with_tc.ovpn && ip route add default via 80.240.24.18 dev eth0"

networks:
  vpn_net:
    driver: macvlan
    driver_opts:
      parent: enp8s0  # Inbound interface of the host itself
    ipam:
      config:
        - subnet: 10.9.96.0/24
          gateway: 10.9.96.1

  no_tc_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.9.91.0/24
          gateway: 10.9.91.1
  tc_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.9.92.0/24
          gateway: 10.9.92.1